import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import {
  ChangeEvent,
  FormEvent,
  useState,
} from 'react'

export default function Home() {
  const [query, setQuery] = useState('')
  const [results, setResults] = useState<any[]>([]) // NOTE: cargo culted type.

  const handleInputChange = (event: ChangeEvent<HTMLInputElement>) => {
    setQuery(event.target.value)
  }

  const handleSubmit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault()
      try {
        const response = await fetch(`https://rv3come0o0.execute-api.us-east-1.amazonaws.com/Prod/${query}`)
          const data = await response.json()
          setResults(data.hits.hits)
      } catch (error) {
        console.log(error)
      }
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gray-100 p-4">
        <form onSubmit={handleSubmit} className="flex flex-col md:flex-row items-center space-y-4 md:space-y-0 md:space-x-4">
          <label htmlFor="search" className="font-medium">Search:</label>
          <input type="text" id="search" value={query} onChange={handleInputChange} className="border border-gray-299 rounded-lg py-2 px-4 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent" />
          <button type="submit" className="bg-blue-500 hover:bg-blue-600 text-white rounded-lg py-2 px-4 font-medium">Search</button>
        </form>
        <div id="search-results" className="mt-8 space-y-4">
          {results && results.map((result) => (
            <div className="bg-white shadow-sm rounded-lg p-4" key={result._id}>
              <div className="text-lg font-medium">
                <a href={`https://youtube.com/watch?v=${result._source.videoId}&t=${result._source.timestamp}`} className="hover:text-blue-500">{result._source.videoTitle}</a>
              </div>
              <div className="text-gray-500 mt-2">
                {`https://youtube.com/watch?v=${result._source.videoId}&t=${result._source.timestamp}`}
              </div>
              <div className="mt-2">
                {result._source.text}
              </div>
            </div>
          ))}
        </div>
      </main>
    </>
  )
}

